### ISSUE TITLE
[Suggestion]把.zip里面的文件 分别上传

### ISSUE THREAD

**Issue by LovelyCatHyt** [YunxiuXu/Virus-School#2]
终于找到了在Github上的源码, 然后一看是个".zip"...
虽然说不影响下载使用,但其实和Git的思想相悖了
Github的正确用法应该是每个文件逐个上传
可以下载一个[Github Desktop](https://desktop.github.com/)试试.
使用git进行版本控制可以很方便地对各个文件(特别是代码)进行不同版本的管理,以及多人协作

**Comment by 956237586** [comment]
帮作者发的：你们的问题作者已经知道，但TA现在的网络环境特别不好，以及回消息忙的不行，所以没有时间改，谢谢大家
