### ISSUE TITLE
请不要上传zip

### ISSUE THREAD

**Issue by buger404** [YunxiuXu/Virus-School#4]
**请不要上传zip**。。。。。
Github原本就是上传代码的地方。。。。。
请**不要把github当网盘用**（X

**Comment by LovelyCatHyt** [comment]
这跟我的issue #2 有啥区别🐎

**Comment by 956237586** [comment]
帮作者发的：你们的问题作者已经知道，但TA现在的网络环境特别不好，以及回消息忙的不行，所以没有时间改，谢谢大家

**Comment by buger404** [comment]
。。。。重复issue应该没问题？

**Comment by sdcb** [comment]
作者想上传什么就上传什么，就算想不上传……也说不了什么。

**Comment by ExerciseBook** [comment]
可close了
（往上看全是熟人，我的妈呀
